# cloudbuild.yaml
steps:
# 1️⃣ Build Docker image for the pipeline
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/PROJECT_ID/ml-pipeline:$SHORT_SHA', '.']

# 2️⃣ Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PROJECT_ID/ml-pipeline:$SHORT_SHA']

# 3️⃣ Run unit tests inside the container (CI)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--rm'
    - 'gcr.io/PROJECT_ID/ml-pipeline:$SHORT_SHA'
    - 'pytest'
    - 'tests/'

# 4️⃣ Deploy to Vertex AI only if tests pass (CD)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Tests passed. Deploying pipeline..."
      # Example: deploy your Vertex AI pipeline here
      # gcloud ai pipelines create --file=pipelines/pipeline.py \
      #     --location=us-central1 \
      #     --pipeline-root=gs://YOUR_BUCKET/pipeline_root

# Optional: define images for build artifacts
images:
  - 'gcr.io/PROJECT_ID/ml-pipeline:$SHORT_SHA'
